class AppRoutes {
  const AppRoutes._();

  static const splash = '/';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const verifyEmail = '/verify-email';
  static const changePassword = '/change-password';
  static const setupProfile = '/setup-profile';
  static const root = '/root';
  static const home = '/home';
  static const courses = '/courses';
  static const roadmaps = '/roadmaps';
  static const search = '/search';
  static const profile = '/profile';
  static const editProfile = '/edit-profile';
  static const profileResetPassword = '/profile-reset-password';
  static const settings = '/settings';
  static const themeSettings = '/settings/theme';
  static const languageSettings = '/settings/language';
  static const mentorToneSettings = '/settings/mentor-tone';
  static const careerGoalSettings = '/settings/career-goal';
  static const helpCenter = '/settings/help-center';
  static const privacyPolicy = '/settings/privacy-policy';
  static const termsOfService = '/settings/terms-of-service';
  static const notifications = '/notifications';
  static const cvUpload = '/cv-upload';
  static const cvAnalysisResult = '/cv-analysis-result';
  static const roadmapDetails = '/roadmap-details';
  static const courseDetails = '/course-details';
  static const jobs = '/jobs';
  static const jobDetails = '/job-details';
  static const coverLetterGenerator = '/cover-letter-generator';
  static const coverLetterResult = '/cover-letter-result';
  static const aiChat = '/ai-chat';
  static const interviewStart = '/interview-start';
  static const activeInterview = '/active-interview';
  static const interviewHistory = '/interview-history';
  static const interviewResult = '/interview-result';
}
